
import data
from sklearn import linear_model as lmodel
from sklearn import preprocessing as pre
from sklearn.impute import KNNImputer
from sklearn import feature_selection as featsel
from sklearn import pipeline as pipe

def build_model():
    imputer = KNNImputer().set_output(transform='polars')
    std = pre.StandardScaler().set_output(transform='polars')
    kbest = featsel.SelectKBest(score_func=featsel.mutual_info_regression, k=100).set_output(transform='polars')
    regressor = lmodel.ElasticNetCV(l1_ratio=[0.1, 0.2, 0.5, 0.8, 0.9], alphas=10, max_iter=2000)
    pipeline = pipe.Pipeline(
        [("impute", imputer),
         ("standarize", std),
         ("k-select features", kbest),
         ("regressor", regressor)
        ]
    )
    return pipeline
    

if __name__ == '__main__':
    # rng seeds generated by numpy
    rng_seeds = [781, 316, 869, 115,  38, 344,  88]
    scores = []
    for seed in rng_seeds:
        x_train, x_test, y_trains, y_tests = data.prepare_datasets(False, rng_seed=seed)
        assert False
        x_train = data.numerize_predictors(x_train)
        x_test = data.numerize_predictors(x_test)
        y_train, x_train2 = data.clear_null_response(y_trains['SK gH2AX'], x_train)
        y_test, x_test2 = data.clear_null_response(y_tests['SK gH2AX'], x_test)
        model = build_model()
        model.fit(x_train2, y_train.log10())
        score = model.score(x_test2, y_test.log10())
        print(score)
        scores.append(score)
    
    assert False
    
    scores = []
    for seed in rng_seeds:
        x_train, x_test, y_trains, y_tests = data.prepare_datasets(False, rng_seed=seed)
        x_train = data.numerize_predictors(x_train)
        x_test = data.numerize_predictors(x_test)
        y_train, x_train2 = data.clear_null_response(y_trains['SK p21'], x_train)
        y_test, x_test2 = data.clear_null_response(y_tests['SK p21'], x_test)
        model = build_model()
        model.fit(x_train2, y_train.log10())
        score = model.score(x_test2, y_test.log10())
        print(score)
        scores.append(score)